import org.jetbrains.kotlin.gradle.tasks.UsesKotlinJavaToolchain

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.1.0/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    kotlin("jvm") version "2.2.20"
}

repositories {
    mavenCentral()
}

subprojects {
    apply(plugin = "kotlin")

    kotlin {
        jvmToolchain(21)
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        val implementation by configurations
        val testImplementation by configurations

        implementation(kotlin("stdlib"))
        testImplementation(kotlin("test"))
        testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
        testImplementation("com.willowtreeapps.assertk:assertk:0.28.1")
        testImplementation("io.kotest:kotest-assertions-core:6.0.3")
        testImplementation("ch.tutteli.atrium:atrium-fluent:1.2.0")
    }

    tasks.withType<Test> {
        useJUnitPlatform()
    }
}