/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.1.0/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "testing-workshop"

include("felles")
include("del1-assertions")
include("del2-mocking")
include("del3-mockless")
include("del4-integration-architecture")

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version("0.9.0")
}